language: php

php:
  - 5.4

env:
  - CODECEPTION_VERSION="1.6.*"
  - CODECEPTION_VERSION="dev-master"

before_script:
  - composer install -n --prefer-dist --dev
  - composer require codeception/codeception:${CODECEPTION_VERSION}

script: "bin/codecept run"
